---
- name: "Initial Setup"
  hosts: all
  become: true
  tasks:
    - name: "Append host:~/.ssh/id_rsa.pub to box:~/.ssh/authorized_keys"
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/michael/.ssh/id_rsa.pub') }}"

    - name: Update modules with virtio drivers
      replace:
        path: /etc/mkinitcpio.conf
        regexp: '(\s+)MODULES=\(\)(\s+.*)?$'
        replace: '\1MODULES=(virtio virtio_pci virtio_blk virtio_net virtio_ring)\2'
        backup: no

    - name: Run mkinitcpio
      shell: mkinitcpio -p linux

    - name: Attach datacenter.local DNS to network interface
      replace:
        path: /etc/systemd/network/eth1.network
        regexp: '(\s+)DHCP=ipv4(\s+.*)?$'
        replace: '\1DHCP=ipv4\nDomains=datacenter.local ~local\2'
        backup: no

    - name: use global DNS
      replace:
        path: /etc/systemd/resolved.conf
        regexp: '(\s+)#DNS=(\s+.*)?$'
        replace: '\1DNS=1.1.1.1 1.0.0.1\2'
        backup: no
