- name: Create a network
  community.docker.docker_network:
    name: mongo
    attachable: yes
    driver: overlay
    ipam_config:
      - subnet: 11.0.0.0/24
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Create a network
  community.docker.docker_network:
    name: mongos
    attachable: yes
    driver: overlay
    ipam_config:
      - subnet: 12.0.0.0/24
  when: inventory_hostname == groups['swarm_managers'][0]
