- name: Copy registry image to swarm manager
  copy:
    src: registry.tar.xz
    dest: /tmp/registry.tar.xz
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Copy mongo image to swarm_manager manager
  copy:
    src: mongo.tar.xz
    dest: /tmp/mongo.tar.xz
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Load registry image from archive
  docker_image:
    name: registry:latest
    load_path: /tmp/registry.tar.xz
    state: present
    source: load
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Start registry service
  docker_swarm_service:
    name: registry
    image: registry
    publish:
      - { published_port: 5000, target_port: 5000 }
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Load mongo image from archive
  docker_image:
    name: mongo
    repository: 127.0.0.0:5000/mongo
    tag: 5.0.6-focal
    load_path: /tmp/mongo.tar.xz
    state: present
    source: load
    push: yes
  when: inventory_hostname == groups['swarm_managers'][0]
