all:
  children:
    ungrouped: {}
    datacenter:
      hosts:
        manager-01.datacenter.local:
        manager-02.datacenter.local:
        data-01.datacenter.local:
          mongo_id: d-01
          is_router: no
        data-02.datacenter.local:
          mongo_id: d-02
          is_router: no
        data-03.datacenter.local:
          mongo_id: d-03
          is_router: no
        config-01.datacenter.local:
          mongo_id: c-01
          is_router: no
        config-02.datacenter.local:
          mongo_id: c-02
          is_router: no
        config-03.datacenter.local:
          mongo_id: c-03
          is_router: no
        router-01.datacenter.local:
          mongo_id: q-01
          is_router: yes
        router-02.datacenter.local:
          mongo_id: q-02
          is_router: yes
    swarm_managers:
      hosts:
        manager-[01:02].datacenter.local:
    swarm_workers:
      hosts:
        data-[01:03].datacenter.local:
        config-[01:03].datacenter.local:
        router-[01:02].datacenter.local:
    app_workers:
      hosts:
        router-[01:02].datacenter.local:
