---
- hosts: mongo_config:mongo_router:mongo_data
  gather_facts: no
  roles:
    - mongo_dependencies

- hosts: mongo_config
  roles:
    - mongo_config

- hosts: mongo_data
  roles:
    - mongo_data

- hosts: mongo_router
  roles:
    - mongo_router
